### ISSUE TITLE
jsum@0.1.1 package in npm is 22MB and contains 180MB test file

### ISSUE THREAD

**Issue by ksuszka** [fraunhoferfokus/JSum#1]
Compressed version of jsum package available in npm registry is 22MB and after decompression it contains 180MB unnecessary file.

**Comment by yan-foto** [comment]
I don't even know where to begin 😅 The package doesn't even have a dependency. The test file has only 46 lines of code! For some reason 'npm publish' has also published the test json file that I've been using locally (missing on git). Thanks for letting me know

**Comment by yan-foto** [comment]
I got it fixed :)
