### ISSUE TITLE
Replicable Hash Collisions

### ISSUE THREAD

**Issue by zkldi** [fraunhoferfokus/JSum#6]
The custom JSON serialize algorithm does not produce necessarily unique output, and therefore can cause hash collisions.

```js
serialise({a: 1, b: 2});
// "a:1|b:2"

serialise({a: "1|b:2"})
// "a:1|b:2"
```

**Comment by zkldi** [comment]
This is also not type safe:
```js
serialise({a: 1});
// "a:1"

serialise({a: "1"});
// "a:1"
```

**Comment by yan-foto** [comment]
This is known to me, check out the example in `README.md`. It might be worth explicitly mentioning in the readme or creating a "fix". Do you care to submit a PR?

**Comment by yan-foto** [comment]
@zkldi checkout changes in `develop`. It might be just what you are looking for. Thanks for reporting this issue and let me know if the changes solve the problem.

**Comment by zkldi** [comment]
Hi, I do believe that works for all scenarios.

This should be okay!

Other than that - this will probably have to be a semver major change, as some people (me) might be depending on the output of JSum to identify json objects.
