### ISSUE TITLE
Replicable hash collisions

### ISSUE THREAD

**Issue by kukawski** [fraunhoferfokus/JSum#8]
The following values have identical hashes, because `stringify` returns the same value.

```
console.log(
  digest({a:'1',b:'2'}, 'SHA256', 'hex'),
  digest({a:'1"\u0000b:\"2'},'SHA256', 'hex'),
  digest({'a:"1"\u0000b':'2'}, 'SHA256', 'hex')
);
```

**Comment by kukawski** [comment]
This could be avoided if string values and key would be `JSON.stringified`.
Specifically turn

    return `"${obj}"`

into

    return JSON.stringify(obj);

and

    acc[i] = `${k}:${stringify(obj[k])}`

into

    acc[i] = `${JSON.stringify(k)}:${stringify(obj[k])}`

**Comment by yan-foto** [comment]
`stringify` is not as fast as I'd like it to be. Moreover, the strings that you are provide might be valid JS objects but definitely (or at least 99% surely!) no valid JSONs (can you save it in a file and read it with `JSON.parse()`?) and as such not relevant for this module.

Let me know if I you think I got it wrong! Cheers.

**Comment by kukawski** [comment]
Even though NULL character can't occur directly in JSON document, it can be part of JSON string values in UnicodeEscapeSequence (`\uXXXX`) form.
Example JSON content that parses to one of example objects from issue description `{a:'1"\u0000b:\"2'}` looks following

    {"a":"1\"\u0000b:\"2"}

**Comment by yan-foto** [comment]
So for:

```json
{"a": 1, "b": 2}
```

I get `a647d1910a4395d01d7036d6fe26cc792d97a480ad3e2209c80e93f0d4a6793b`, and for:

```json
{"a":"1\"\u0000b:\"2"}
```

I get `92777e68d424775c05323e81ba30c0a0f92b9e694eed9c995be08d32fbb58b62`.

Where's the collision? If you look at #6 and #7, there have been similar issues with previous implementations but since the latest version the null character is used is delimiter to make sure that it does not occur in any JSON file.

Am I still missing something?

**Comment by yan-foto** [comment]
I think I know what you are getting at, these cases would return the same string/hash:

```JSON
{"a":1,"b":2}
{"a:1\u0000b":2}
```

**Comment by kukawski** [comment]
> So for:
> 
> ```json
> {"a": 1, "b": 2}
> ```
> 
> I get `a647d1910a4395d01d7036d6fe26cc792d97a480ad3e2209c80e93f0d4a6793b`, and for:
> ...
> Am I still missing something?

Yes, you're missing the apostrophes around the numbers. The JS object should be `{a:'1',b:'2'}` (encoded in JSON: `{"a":"1","b":"2"}`).

**Comment by yan-foto** [comment]
I think the easiest solution to this would be to enclose the keys with some additional character so in the final string the border between keys and values is always clear so here:

https://github.com/fraunhoferfokus/JSum/blob/faa28f844151700be4c813648185000929f2aab3/index.js#L33

you'd have `"${k}":${stringify(obj[k])}`

**Comment by yan-foto** [comment]
A side note: do you have such cases in your application or do you want to use this module in a security critical environment?

**Comment by kukawski** [comment]
> I think the easiest solution to this would be to enclose the keys with some additional character so in the final string the border between keys and values is always clear so here:

I'm afraid it's not going to be enough. Assuming you use quotes to surround `${k}`, I think you also need to escape all quotes inside `k`. The same applies to `obj` in `"${obj}"`, otherwise there will always be ways to construct such values for both variables that make `JSum.stringify` generate the same output. It's just a matter of playing with `"` and `\u0000` in keys and string values.

> A side note: do you have such cases in your application or do you want to use this module in a security critical environment?

Actually a teammate stumbled upon this module when searching for function to generate "stable" JSON strings (with sorted object keys).

**Comment by yan-foto** [comment]
> I'm afraid it's not going to be enough. Assuming you use quotes to surround `${k}`, I think you also need to escape all quotes inside `k`. The same applies to `obj` in `"${obj}"`, otherwise there will always be ways to construct such values for both variables that make `JSum.stringify` generate the same output.

You're right: every delimiter that can be part of a key or value can be abused to generate hash collisions. And you're right again that the delimiter needs to be escaped. This would, however, make things *really really slow*. I would prefer to have some delimiter that cannot be presented through escaped unicode than using `JSON.stringify`. Any ideas?

**Comment by yan-foto** [comment]
> Alternatively, you can use `String.prototype.replace` with a regex to escape all quotes. Didn't check the performance impact.

Forgot to mention: I already checked that out (`replaceAll`) and although it's faster than `JSON.stringify`. It is still very slow. I'm running out of ideas here!

**Comment by kukawski** [comment]
Unfortunately, I also can't find any other solution that doesn't impact performance.

**Comment by yan-foto** [comment]
So, it turns out that no UTF-8 code point actually maps to `0xff` and `0xfe` (I finally got myself familiarized with UTF), my Idea (see hotfix branch) is to use these two as delimiters and be sure that they cannot be escaped using `\uxxxx`. What do you think?

**Comment by yan-foto** [comment]
I think there's still an error in my solution that needs fixing... I should use Buffers instead of strings.

**Comment by yan-foto** [comment]
> `stringify` is not as fast as I'd like it to be.

I stand corrected: `JSON.stringify()` turns out to be fastest solution when it comes to serializing and string escaping! I threw away everything that I had written from the scratch and replaced them with `JSON.stringify()` and simply used the [`replacer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#parameters) parameter to sort the object keys!

Thanks for submitting this issue! Version [`2.0.0-alpha.1`](https://www.npmjs.com/package/jsum/v/2.0.0-alpha.1) is 2x faster than before!

**Comment by kukawski** [comment]
I've briefly checked the new implementation and I think it - unfortunately - still suffers from replicable hash collisions.
Please check the following two JavaScript values that serialize the same way

```
serialize([{foo:1}]); // array of objects
serialize(['{"foo":1}']); // array of strings
```

It's not limited to objects in arrays only, but also to objects inside objects.

What you can do is to iterate over the whole structure and collect all object keys. Sort the list of keys and then run `JSON.stringify()` once on the entire data passing the sorted keys as second param.

**Comment by yan-foto** [comment]
Thanks for sticking around and keeping on putting holes in this project :+1: I think the cause of this problem is the conditional that was supposed to be a performance improvement:

https://github.com/fraunhoferfokus/JSum/blob/52026a494662429d50111a8667b5ea19083de89d/index.js#L33-L36

Serializing the whole result using `JSON.stringify` would solve this very specific situation, right?

```
> jsum.serialize([{"foo":1}])
'[{"foo":1}]'
> jsum.serialize(['{"foo":1}'])
'["{\\"foo\\":1}"]'
> jsum.serialize({a: {b:42}})
'{"a":{"b":42}}'
> jsum.serialize({a: '{"b":42}'})
'{"a":"{\\"b\\":42}"}'
```

By the way, this is the very reason that I didn't use `JSON.stringify` in the first place: it doesn't work with nested structures so I suppose that you need to start to sort/stringify from the most bottom level all the way to the top. To fool this method you'd just put a stringified value somewhere in the first level and you got your hash collisions. If my logic holds, a final escaping would solve this problem. What do you think?

**Comment by kukawski** [comment]
The main issue with your new approach is that you serialize nested objects to string and then serialize data that contains the already serialized objects. The output was not the exact JSON that you would get by calling standard `JSON.stringify` on whole data and the fact that objects are at some point a string, it is easy to provide another value that serializes to the same form

> By the way, this is the very reason that I didn't use JSON.stringify in the first place: it doesn't work with nested structures

The `JSON.stringify` API is kind of limited, but it works with nested structures. When using an array of keys as the replacer param, it is AFAIK used on every nested object to filter properties to serialize. That's why I suggested to collect all keys, which can be achieved with

```js
function collectObjectKeys(root) {
  if (Array.isArray(root)) {
    return root.map((item) => collectObjectKeys(item)).reduce((acc, item) => acc.concat(item), []);
  } else if (typeof root === "object" && root !== null) {
    return Object.keys(root).concat(Object.values(root).map(collectObjectKeys).reduce((acc, item) => acc.concat(item), []));
  }
  return [];
}
```
Then your `JSUM.stringify` could have the form

```js
JSUM.stringify = function (data) {
  const keys = collectObjectKeys(data);
  return JSON.stringify(data, keys.sort());
}
```

This way, according to my knowledge, we should always get a correct JSON string, which is stable because of the sorted keys, because of how [ECMAScript spec describes the algorithm](https://tc39.es/ecma262/multipage/structured-data.html#sec-serializejsonobject).

The only thing left to consider is to handle cycles in `collectObjectKeys`.

**Comment by yan-foto** [comment]
> The main issue with your new approach is that you serialize nested objects to string and then serialize data that contains the already serialized objects.

It works, but it doesn't scale anyhow.

> That's why I suggested to collect all keys, which can be achieved with

Oh, sorry! I didn't exactly understood what you meant. I'll give it a try. If that's the case, then we have no problems anymore!

**Comment by yan-foto** [comment]
You did what I should've done before discarding the idea of using `replacer`: checking out the documentation and the actual implementation! Now that everything works as expected, the slowest part of this approach is actually collecting the keys... (6 times slower than `fast-json-stable-stringify`)

I'm currently looking for ways to optimize this.

> This way, according to my knowledge, we should always get a correct JSON string, which is stable because of the sorted keys, because of how [ECMAScript spec describes the algorithm](https://tc39.es/ecma262/multipage/structured-data.html#sec-serializejsonobject).

btw the correct section is here:

https://tc39.es/ecma262/multipage/structured-data.html#sec-json.stringify

**Comment by kukawski** [comment]
> You did what I should've done before discarding the idea of using `replacer`: checking out the documentation and the actual implementation! Now that everything works as expected, the slowest part of this approach is actually collecting the keys... (6 times slower than `fast-json-stable-stringify`)

I didn't measure the performance, but I'm a bit surprised that `collectObjectKeys` alone would be 6 times slower than `fast-json-stable-stringify`. Anyway, there is room for improvement, because the function in current form makes many memory allocations, there are many callbacks, etc.
First approach for improving could be to use simple `for of` loops to iterate (avoids defining new functions and calling them all the time). Also, collected keys could be passed to recursive calls as param and that array would be populated (less memory allocations). Something like the below (didn't test it thoroughly):

```js
function collectObjectKeys(root, collectedKeys = []) {
  if (Array.isArray(root)) {
    for (const v of root) {
      collectObjectKeys(v, collectedKeys);
    }
  } else if (typeof root === "object" && root !== null) {
    const keys = Object.keys(root);
    for (const key of keys) {
      collectedKeys.push(key);
      collectObjectKeys(root[key], collectedKeys);
    }
  }

  return collectedKeys;
}
```

> > This way, according to my knowledge, we should always get a correct JSON string, which is stable because of the sorted keys, because of how [ECMAScript spec describes the algorithm](https://tc39.es/ecma262/multipage/structured-data.html#sec-serializejsonobject).
> 
> btw the correct section is here:
> 

The link that I provided pointed to the part of JSON serialization that mentiones how _replacer array_ is used as proof that it should serialize props in the wanted order.

**Comment by yan-foto** [comment]
I tried both suggestions:

1. tail recursion using accumulators
2. `of` instead of `for`

Tail recursion improves the performance but not as much as needed, and it turns out (to my own surprise) that `for` is faster than `of`:

```
  for x 29,830,711 ops/sec ±1.35% (87 runs sampled)
  of x 26,562,782 ops/sec ±0.78% (90 runs sampled)

  fastest is for
```

Actually the culprit is push. I suppose that `push` increases the array size, triggering new memory allocation and since array members are strings of various length, it takes a good while to manage it. That said, I'm not really familiar with internal workings of V8 engine!

**Comment by yan-foto** [comment]
I suppose the key is to have a string accumulator rather than an array.

**Comment by kukawski** [comment]
The "crazy serialization" approach serializes the both values the same way

```js
console.log(_serialize({foo:1, bar: 2}));
console.log(_serialize([{foo:1, bar:2}]));
```

**Comment by yan-foto** [comment]
> The "crazy serialization" approach serializes the both values the same way
> 
> ```js
> console.log(_serialize({foo:1, bar: 2}));
> console.log(_serialize([{foo:1, bar:2}]));
> ```

Are you sure?

```js
> jsum.serialize({foo:1, bar: 2})
'{["bar","foo"]21}'
> jsum.serialize([{foo:1, bar:2}])
'[{["bar","foo"]21}]'
```
:point_up_2: this is what I see :-/

**Comment by kukawski** [comment]
My fault, I just checked the code from the commit linked above my previous comment. The latest branch state doesn't have this issue.
I will have a look at the branch later today.

**Comment by kukawski** [comment]
Hi. I had a look at the code. I did manage to generate a collision. Please have a look at the two example calls

```js
console.log(serialize({x:1,y:23}));
console.log(serialize({x:12,y:3}));
```
Both return `{["x","y"]123}`.

**Comment by yan-foto** [comment]
I'm pretty sure that I had the exact same issue somewhere down the road and fixed it. Obviously it got overwritten again :upside_down_face: I'll fix this and most probably remove `acc`. Otherwise I think the rest is simple enough so that further collisions are avoidable.
